реализован task read
craftyard/front-core-run pull request #3
Opened 2023-10-17 12:20 UTC by Renatter

2023-10-17 12:28 UTC, FredSteady23 approved these changes

2023-10-17 12:43 UTC, yaksh0nti requested changes

2023-10-17 12:43 UTC, yaksh0nti commented on package.json
> +  "name": "workshop",
нвдо изменить на front, workshop будет как модуль в этом репозиторий

2023-10-18 10:59 UTC, NurGeo approved these changes

2023-10-18 10:59 UTC, NurGeo commented on package.json
> +    "rxjs": "~7.8.0",
предлагаю, поставить в зависимости

2023-10-18 11:00 UTC, NurGeo commented on package.json
> +  "name": "workshop",
workshop-front??

2023-10-19 11:48 UTC, yaksh0nti commented on package.json
> +    "rxjs": "~7.8.0",
что?

2023-10-19 11:50 UTC, yaksh0nti approved these changes

2023-10-20 13:21 UTC, merged